# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: minesweeper
# "service" is the name of this project. This will also be added to your AWS resource names.
service: minesweeper

provider:
  name: aws
  runtime: python3.11
  profile: peter-personal

functions:
  hello:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          path: /genboard
          method: get
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /hint
          method: post
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

plugins:
  - serverless-offline
