# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hanai
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: minesweeper
# "service" is the name of this project. This will also be added to your AWS resource names.
service: minesweeper

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
